flaskblog/main/routes.py
from flask import Blueprint, request, render_template
from flaskblog.models import Post
from flaskblog.posts.routes import has_user_liked_posts
from flask_login import current_user

main = Blueprint('main', __name__)



@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page',1,type=int)
    posts = Post.query.order_by(Post.date_created.desc()).paginate(per_page=5,page=page)
    has_liked_posts = has_user_liked_posts(current_user.id, list(map(lambda post: post.id, posts.items))) if current_user.is_authenticated else {}
    return render_template('home.html', posts=posts, has_liked_posts=has_liked_posts)

@main.route("/about")
def about():
    return render_template('about.html', title='About')

flaskblog/posts/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Comment, Post, Reaction
from flaskblog.posts.forms import PostForm, CommentForm

posts = Blueprint('posts', __name__)



@posts.route("/post/new",methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,content=form.content.data,author=current_user)
        db.session.add(post)
        current_user.posts_count += 1
        db.session.commit()
        flash('Posted on your blog.','success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='Create Post', legend='New Post', form=form)

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    has_liked = has_user_liked_post(current_user.id, post_id) if current_user.is_authenticated else None
    return render_template('post.html',title=post.title, post=post, has_liked=has_liked)

@posts.route('/post/<int:post_id>/update', methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your Post has been updated.','success')
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html',title='Update Post', legend='Update Post', post=post, form=form)

@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    current_user.posts_count -= 1
    db.session.commit()
    flash('Your Post has been deleted.','success')
    return redirect(url_for('main.home'))

# should the method be GET or POST
@posts.route('/post/<int:post_id>/react_on_post/<int:has_liked_int>', methods=['GET'])
@login_required
def react_on_post(post_id, has_liked_int):
    has_liked = False if has_liked_int==0 else True
    react_on_post_util(post_id, has_liked)
    flash('Your reaction on post has been saved.','success')
    return redirect(f'{request.referrer}#post-{post_id}')


@posts.route('/post/<int:post_id>/comment/new', methods=['GET','POST'])
@login_required
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(content=form.content.data, post_id=post_id, user_id=current_user.get_id())
        post.comments_count += 1
        db.session.add(comment)
        flash('Successfully added your comment!','success')
        return redirect(url_for('post.post',post_id=post_id))
    return render_template('create_comment.html',title='Create Comment', legend='New Comment', form=form)


# should the method be GET or POST
@posts.route('/post/<int:post_id>/comment/<int:comment_id>/react_on_comment/<int:has_liked_int>', methods=['GET'])
@login_required
def react_on_comment(post_id, comment_id, has_liked_int):
    comment = Comment.query.get_or_404(comment_id)
    has_liked = False if has_liked_int==0 else True

    # checking if user has already reacted on this comment
    reaction = Reaction.query.filter_by(comment_id=comment_id, on_post=False, user_id=current_user.get_id()).first()
    
    if reaction is None:
        reaction = Reaction(on_post=False, has_liked=has_liked, user_id=current_user.get_id(), comment_id=comment_id)
        if has_liked:
            comment.likes_count += 1
        else:
            comment.dislikes_count += 1
        db.session.add(reaction)
    else:
        if reaction.has_liked == True and has_liked == False:
            comment.likes_count -= 1
            comment.dislikes_count += 1
            reaction.has_liked = has_liked
        elif reaction.has_liked == False and has_liked == True:
            comment.dislikes_count -= 1
            comment.likes_count += 1
            reaction.has_liked = has_liked
        elif reaction.has_liked == True and has_liked == True:
            comment.likes_count -= 1
            db.session.delete(reaction)
        elif reaction.has_liked == False and has_liked == False:
            comment.dislikes_count -= 1
            db.session.delete(reaction)
    db.session.commit()
    flash('Your reaction on comment has been saved.','success')
    return redirect(f'{request.referrer}post-#{post_id}')


@posts.route('/api/post/react_on_post', methods=['POST'])
@login_required
def react_on_post_api():
    content_type = request.headers.get('Content-Type')
    if (content_type != 'application/json'):
        abort(400)
    json = request.json
    return react_on_post_util(json.get('post_id'), json.get('has_liked'))


def react_on_post_util(post_id, has_liked):
    post = Post.query.get_or_404(post_id)
    # checking if user has already reacted on this post
    reaction = Reaction.query.filter_by(post_id=post_id, on_post=True, user_id=current_user.get_id()).first()
    
    if reaction is None:
        reaction = Reaction(on_post=True, has_liked=has_liked, user_id=current_user.get_id(), post_id=post_id)
        if has_liked:
            post.likes_count += 1
        else:
            post.dislikes_count += 1
        db.session.add(reaction)
    else:
        if reaction.has_liked == True and has_liked == False:
            post.likes_count -= 1
            post.dislikes_count += 1
            reaction.has_liked = has_liked
        elif reaction.has_liked == False and has_liked == True:
            post.dislikes_count -= 1
            post.likes_count += 1
            reaction.has_liked = has_liked
        elif reaction.has_liked == True and has_liked == True:
            post.likes_count -= 1
            db.session.delete(reaction)
        elif reaction.has_liked == False and has_liked == False:
            post.dislikes_count -= 1
            db.session.delete(reaction)
    db.session.commit()
    return {'likes':post.likes_count, 'dislikes':post.dislikes_count}

def has_user_liked_post(user_id, post_id):
    reaction = Reaction.query.filter_by(post_id=post_id, on_post=True, user_id=user_id).first()
    has_liked = reaction.has_liked if reaction else None
    return has_liked

def has_user_liked_posts(user_id, post_id_list):
    # pass only Reaction class to with_entities to get all coulumns
    reactions = Reaction.query.with_entities(Reaction.post_id, Reaction.has_liked).filter(Reaction.user_id==user_id, Reaction.post_id.in_(post_id_list), Reaction.on_post==True).all()
    has_liked_post = {}
    for reaction in reactions:
        has_liked_post.update({reaction.post_id: reaction.has_liked})
    return has_liked_post

flaskblog/users/routes.py
import json
from flask import Blueprint, render_template, url_for, flash, redirect, request, session
from flask_login import login_user, logout_user, current_user, login_required
from flaskblog import db, bcrypt
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetRequestForm, ResetPasswordForm, ChangePasswordForm
from flaskblog.models import User, Post
from flaskblog.users.utils import get_google_auth, save_picture, send_reset_email, username_from_email, save_picture_from_url
from flaskblog.config import Auth
from flaskblog.reference import profile_pics_predef
from flaskblog.posts.routes import has_user_liked_posts


users = Blueprint('users', __name__)

@users.route("/register",methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(first_name=form.first_name.data,last_name=form.last_name.data,username=form.username.data,email=form.email.data,password=hashed_password,login_using='Password')
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash(f'Welcome, {user.username}.','success')
        next_page = request.args.get('next')
        return redirect(next_page) if next_page else redirect(url_for('main.home'))
    return render_template('register.html', title="Sign Up", form=form)

@users.route("/login/<prompt>")
@users.route("/login",methods=['GET','POST'])
def login(prompt=None):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('Invalid Password','danger')
        elif user.login_using!='Password':
            flash(f'You have used {user.login_using} to login before. Please use the same to login!','danger')
        else:
            if bcrypt.check_password_hash(user.password,form.password.data):
                login_user(user, remember=form.remember.data)
                flash(f'Welcome {user.username}. You are now logged in.','success')
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
            else:
                flash('Invalid Password','danger')
    oauth = get_google_auth()
    auth_url, state = oauth.authorization_url(Auth.AUTH_URI, access_type='offline', prompt=prompt)
    session['oauth_state'] = state
    return render_template('login.html', title="Login", form=form, auth_url=auth_url)

@users.route("/oauth2callback")
def callback():
    if current_user is not None and current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if 'error' in request.args:
        if request.args.get('error') == 'access_denied':
            flash('You denied access.','danger')
        else:
            flash('Error occured','danger')
        return redirect(url_for('users.login'))
    if 'code' not in request.args or 'state' not in request.args:
        flash('Error Occurred! Please try again.')
        return redirect(url_for('users.login'))
    else:
        print()
        print('code: ', request.args.get('code'))
        print('request.url: ',request.url)
        print()

    oauth = get_google_auth(state=session['oauth_state'])
    try:
        token = oauth.fetch_token(Auth.TOKEN_URI, client_secret=Auth.CLIENT_SECRET, authorization_response=request.url)
    except Exception as e:
        print("Error: ", e)
        flash('Error Occurred while getting access token','danger')
        return redirect(url_for('users.login'))
    resp = oauth.get(Auth.USER_INFO)
    if resp.status_code == 200:
        user_data = resp.json()
        email = user_data['email']
        
        user = User.query.filter_by(email=email).first()
        if user is not None:
            if user.login_using!='Google':
                flash(f'You have not used Google to login before. Please use email and password to login!','danger')
                return redirect(url_for('users.login'))
            flash(f'Welcome back, {user.username}.','success')
            user.login_using = 'Google'
        else:
            user = User()
            user.username = username_from_email(email,User)
            user.first_name = user_data['given_name']
            user.last_name = user_data['family_name']
            user.email = email
            user.avatar_link = user_data['picture']
            user.image_file = save_picture_from_url(user_data['picture'])
            user.tokens = json.dumps(token)
            user.login_using = 'Google'
            flash(f'Welcome, {user.username}.','success')
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('main.home'))       
    else:
        flash('Could not fetch your information','danger')
        return redirect(url_for('users.login'))

@users.route("/logout")
def logout():
    if current_user.is_authenticated:
        flash('Logged out','success')
        logout_user()
    return redirect(url_for('main.home'))

@users.route("/account",methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    password_form = ChangePasswordForm()
    formid = request.args.get('formid',1,type=int)
    if form.validate_on_submit() and formid==1:
        if form.picture.data:
            picture_fn = save_picture(form.picture.data)
            current_user.image_file = picture_fn
        elif form.predef_picture.data in profile_pics_predef:
            current_user.image_file = form.predef_picture.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.dob = form.dob.data
        current_user.gender = form.gender.data
        db.session.commit()
        flash('Your details were updated!','success')
        return redirect(url_for('users.account'))
    elif password_form.validate_on_submit() and formid==2:
        if current_user.login_using!='Password':
            flash(f'You have used {current_user.login_using} to login. Password was not used.','info')
        elif bcrypt.check_password_hash(current_user.password, password_form.current_password.data):
            hashed_password = bcrypt.generate_password_hash(password_form.new_password.data).decode('utf-8')
            current_user.password = hashed_password
            db.session.commit()
            flash('Password updated successfully!','success')
        else:
            flash('Current password entered is incorrect!','danger')
        return redirect(url_for('users.account'))
    if request.method == 'GET':
        form.username.data = current_user.username
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.email.data = current_user.email
        form.dob.data = current_user.dob
        form.gender.data = current_user.gender
    image_file = url_for('static',filename='profile_pics/'+current_user.image_file)
    profile_pics_paths = {}
    for name in profile_pics_predef:
        profile_pics_paths[name] = url_for('static', filename='profile_pics/'+name)
    return render_template('account.html', title='Account', image_file=image_file, profile_pics_paths=profile_pics_paths, form=form, password_form=password_form)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_created.desc())\
        .paginate(per_page=5,page=page)
    has_liked_posts = has_user_liked_posts(current_user.id, list(map(lambda post: post.id, posts.items))) if current_user.is_authenticated else {}
    return render_template('user_posts.html', posts=posts, user=user, has_liked_posts=has_liked_posts)

@users.route("/reset_password", methods=['GET','POST'])
def request_reset_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = ResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        try:
            send_reset_email(user)
        except:
            flash('This serice is currently unavailable','danger')
            return redirect(url_for('users.request_reset_password'))
        flash('Instruction to reset password has been sent to your email.','info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<string:token>", methods=['GET','POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid/Expired token.','warning')
        return redirect(url_for('users.request_reset_password'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password updated successfully!','success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
    <h4>Website developed by <a href="https://www.linkedin.com/in/krishna--choudhary/">Krishna Choudhary</a></h4>
    <h4><a href="https://github.com/krishu1501">Github link</a> for this Website.</h4>

    
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src="{{ url_for('static',filename='profile_pics/'+current_user.image_file) }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
        </div>
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">{{ legend }}</legend>
                    <div class="form-group mb-3">
                        {{ form.title.label(class="form-control-label") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                    <span>{{error}}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group mb-3">
                        {{ form.content.label(class="form-control-label") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{error}}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info ") }}
                </div>
            </form>
    </div>
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Blogpost</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
            <a class="navbar-brand mr-4" href="/">Blogpost</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
            </div>
        </nav>
    </header>
    
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
            {% with messages=get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
            <div class="content-section">
                <h3>Contests</h3>
                <p class='text-muted'>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Most liked post</li>
                    <li class="list-group-item list-group-item-light">Most engaging post</li>
                    <li class="list-group-item list-group-item-light">Most active blogger</li>
                </ul>
                </p>
            </div>
            </div>
        </div>
    </main>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>





    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script> -->

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script> -->
   
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.request_reset_password') }}">Forgot Password?</a>
                </small>
            </div>
            
        </form>
        <div class="form-group">
        <a href="{{ auth_url }}" class="btn btn-lg btn-outline-info btn-block"><img src="{{url_for('static',filename='images/google.png')}}" alt="" height="40" width="40" class="mr-2">Login with Google</a>
        </div>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account?<a href="{{ url_for('users.register') }}" class="ml-2">Sign up</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
{% include "post_helper.html" %}
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
          <input type="submit" class="btn btn-danger" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

flaskblog/templates/post_helper.html
{% extends "post_template.html" %}
{% block editButtons %}
{% if post.author == current_user %}
<div>
  <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
  <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
</div>
{% endif %}
{% endblock editButtons %}

flaskblog/templates/post_template.html
<article class="media content-section" id="post-{{ post.id }}">
    <img class="rounded-circle article-img"
        src="{{ url_for('static',filename='profile_pics/'+post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{
                post.author.username
                }}</a>
            <small class="text-muted">{{ post.date_created.strftime('%Y-%m-%d') }}</small>

            {% block editButtons %}{% endblock editButtons %}

        </div>
        <h2 class="article-title"><a class="article-title" href="{{ url_for('posts.post',post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
        <div class="reactions">
            <div class="btn-group mb-1" role="group">
                <button title="Like" onclick="reactOnPost(`{{url_for('posts.react_on_post_api')}}`,{{post.id}}, true, `{{ url_for('users.login') }}`, {% if current_user.is_authenticated %} true {% else %} false {% endif %})"
                    class="btn {% if has_liked %}btn-primary{% endif %}"><span class="likes-count">{{ post.likes_count }}</span> 👍 </button>
                <button title="Dislike" onclick="reactOnPost(`{{url_for('posts.react_on_post_api')}}`,{{post.id}}, false, `{{ url_for('users.login') }}`, {% if current_user.is_authenticated %} true {% else %} false {% endif %})"
                    class="btn {% if has_liked==False %}btn-primary{% endif %}"><span class="dislikes-count">{{ post.dislikes_count }}</span> 👎 </button>
            </div>
        </div>

    </div>
</article>
<script src="{{ url_for('static',filename='js/post_reactions.js') }}"></script>

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
<h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
{% for post in posts.items %}
  {% set has_liked=has_liked_posts.get(post.id) %}
    {% include "post_template.html" %}
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num
        }}</a>
      {% else %}
      <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
        page_num }}</a>
    {% endif %}
    {% else %}
      ...
  {% endif %}
{% endfor %}
{% endblock content %}